### PR TITLE
Specify explicit jackson dependency

### PR DESCRIPTION
**Pull request by alberto-brigandi**
Using the range notation the build fails because il downloading the wrong library version

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project im-java-api: Compilation failure: Compilation failure:
[ERROR] /var/lib/jenkins/workspace/INDIGO/im-java-api-publish/src/main/java/es/upv/i3m/grycap/im/pojo/deserializer/InfrastructureStateDeserializer.java:[28,54] incompatible types: com.fasterxml.jackson.databind.JsonNode cannot be converted to com.fasterxml.jackson.databind.node.ObjectNode
[ERROR] /var/lib/jenkins/workspace/INDIGO/im-java-api-publish/src/main/java/es/upv/i3m/grycap/im/pojo/deserializer/PropertyDeserializer.java:[21,56] incompatible types: com.fasterxml.jackson.databind.JsonNode cannot be converted to com.fasterxml.jackson.databind.node.ObjectNode

### CODE REVIEW

**Comment by micafer** [comment]
add to whitelist

**Comment by alberto-brigandi** [comment]
Hi @micafer, what tests are failing? I cannot access the logs of the jenkins's job

**Comment by micafer** [comment]
Hi @alberto-brigandi,
It is a problem with maven. In particular this one:
https://stackoverflow.com/questions/59763531/maven-dependencies-are-failing-with-a-501-error

I have to update the maven version in the jenkins server.

**Comment by micafer** [comment]
Hi @alberto-brigandi,
I saw also an error in some tests due to an update in the tosca-types.
I fixed it. So could you merge master changes in your branch?

**Pull request merged**
